name: build

on:
  push:
    branches: [ Release ]
  pull_request:
    branches: [ Release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore **/*.sln
    - name: Build
      run: dotnet build CognitiveComplexityAnalyzer/CCAnalyzer/CCAnalyzer/CCAnalyzer.Package/CCAnalyzer.Package.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test **/*.sln --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
